import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Layout/Navbar";
import TopHeader from "./Components/Layout/TopHeader";
import Footer from "./Components/Layout/Footer";
import Head from "next/head";
import { Josefin_Sans } from '@next/font/google';
import Communication from "./Components/Layout/Communication";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Talal Al Alfi",
  description: "Generated by create next app",
};

const josefinSans = Josefin_Sans({
  subsets: ['latin'], // Choose subsets as per your requirement
  weight: ['400','500' , '600' , '700'], // Choose weights as per your requirement
});

export default function RootLayout({ children }) {
  return (
    <html>
      <Head>
        </Head>
      <body >
      <main className={josefinSans.className}>
        <TopHeader />
        <Navbar />
        <Communication />
        {children}
        <Footer />
      </main>
      </body>
    </html>
  );
}
